/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SecretRouteImport } from './routes/secret'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HobbiesRouteImport } from './routes/hobbies'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsEsp32RouteImport } from './routes/projects.esp32'
import { Route as ProjectsBreraRouteImport } from './routes/projects.brera'
import { Route as ProjectsBravoRouteImport } from './routes/projects.bravo'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretRoute = SecretRouteImport.update({
  id: '/secret',
  path: '/secret',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HobbiesRoute = HobbiesRouteImport.update({
  id: '/hobbies',
  path: '/hobbies',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsEsp32Route = ProjectsEsp32RouteImport.update({
  id: '/projects/esp32',
  path: '/projects/esp32',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBreraRoute = ProjectsBreraRouteImport.update({
  id: '/projects/brera',
  path: '/projects/brera',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsBravoRoute = ProjectsBravoRouteImport.update({
  id: '/projects/bravo',
  path: '/projects/bravo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/hobbies': typeof HobbiesRoute
  '/login': typeof LoginRoute
  '/secret': typeof SecretRoute
  '/skills': typeof SkillsRoute
  '/projects/bravo': typeof ProjectsBravoRoute
  '/projects/brera': typeof ProjectsBreraRoute
  '/projects/esp32': typeof ProjectsEsp32Route
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/hobbies': typeof HobbiesRoute
  '/login': typeof LoginRoute
  '/secret': typeof SecretRoute
  '/skills': typeof SkillsRoute
  '/projects/bravo': typeof ProjectsBravoRoute
  '/projects/brera': typeof ProjectsBreraRoute
  '/projects/esp32': typeof ProjectsEsp32Route
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/experience': typeof ExperienceRoute
  '/hobbies': typeof HobbiesRoute
  '/login': typeof LoginRoute
  '/secret': typeof SecretRoute
  '/skills': typeof SkillsRoute
  '/projects/bravo': typeof ProjectsBravoRoute
  '/projects/brera': typeof ProjectsBreraRoute
  '/projects/esp32': typeof ProjectsEsp32Route
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/experience'
    | '/hobbies'
    | '/login'
    | '/secret'
    | '/skills'
    | '/projects/bravo'
    | '/projects/brera'
    | '/projects/esp32'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/experience'
    | '/hobbies'
    | '/login'
    | '/secret'
    | '/skills'
    | '/projects/bravo'
    | '/projects/brera'
    | '/projects/esp32'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/experience'
    | '/hobbies'
    | '/login'
    | '/secret'
    | '/skills'
    | '/projects/bravo'
    | '/projects/brera'
    | '/projects/esp32'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  ExperienceRoute: typeof ExperienceRoute
  HobbiesRoute: typeof HobbiesRoute
  LoginRoute: typeof LoginRoute
  SecretRoute: typeof SecretRoute
  SkillsRoute: typeof SkillsRoute
  ProjectsBravoRoute: typeof ProjectsBravoRoute
  ProjectsBreraRoute: typeof ProjectsBreraRoute
  ProjectsEsp32Route: typeof ProjectsEsp32Route
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret': {
      id: '/secret'
      path: '/secret'
      fullPath: '/secret'
      preLoaderRoute: typeof SecretRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobbies': {
      id: '/hobbies'
      path: '/hobbies'
      fullPath: '/hobbies'
      preLoaderRoute: typeof HobbiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/esp32': {
      id: '/projects/esp32'
      path: '/projects/esp32'
      fullPath: '/projects/esp32'
      preLoaderRoute: typeof ProjectsEsp32RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/brera': {
      id: '/projects/brera'
      path: '/projects/brera'
      fullPath: '/projects/brera'
      preLoaderRoute: typeof ProjectsBreraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/bravo': {
      id: '/projects/bravo'
      path: '/projects/bravo'
      fullPath: '/projects/bravo'
      preLoaderRoute: typeof ProjectsBravoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  ExperienceRoute: ExperienceRoute,
  HobbiesRoute: HobbiesRoute,
  LoginRoute: LoginRoute,
  SecretRoute: SecretRoute,
  SkillsRoute: SkillsRoute,
  ProjectsBravoRoute: ProjectsBravoRoute,
  ProjectsBreraRoute: ProjectsBreraRoute,
  ProjectsEsp32Route: ProjectsEsp32Route,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
